OPTIONS(skip=1)
LOAD DATA
INFILE      'C:\SQL\POTUS\POTUS.csv'
BADFILE     'C:\SQL\POTUS\POTUS.bad'
DISCARDFILE 'C:\SQL\POTUS\POTUS.dsc'
TRUNCATE
INTO TABLE POTUS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(POTUS_SEQ          INTEGER EXTERNAL,
 FNAME              CHAR(50),
 MNAME              CHAR(50),
 LNAME              CHAR(50),
 START_DT           timestamp "MM/DD/YYYY",
 END_DT             timestamp "MM/DD/YYYY",
 STATE              CHAR(50)
)
